export const dataAtajos = [
  {
    id: 1,
    title: 'ORGANIGRAMA MUNICIPAL',
    img: 'mapa_estado_municipal',
    alt: 'Mapa del estado municipal',
    descripcion: 'Es un diagrama que muestra la estructura jerárquica de funcional del gobierno local, indicando las áreas y sus relaciones. Es un aporte a la transparecia y un acercamiento a la ciudadanía a un gobierno abierto ya que permite conocer la estructura organizativa.',
    link: '../organigrama',
  },
  {
    id: 2,
    title: 'BOLETÍN OFICIAL',
    img: 'boletin_oficial',
    alt: 'Boletín oficial',
    descripcion: 'En esta sección encontrarás las publicaciones oficiales del municipio, como ordenanzas, decretos y resoluciones. Aqui se difuncen las decisiones y acciones importantes del gobierno local para mantenerte informado y garantizar la trasnparencia.',
    link: '../boletin-oficial',
  },
  {
    id: 3,
    title: 'COMPRAS Y LICITACIONES',
    img: 'compra_licitaciones',
    alt: 'Compras y licitaciones',
    descripcion: 'Aquí encontrarás detalles sobre las licitaciones y contratos del municipio. Incluye anuncios de licitaciones, contratos adjudicados, y detalles sobre proveedores y gastos. Esta sección asegura la transparencia al mostrar cómo se adjudican los contratos y se manejan las compras públicas.',
    link: '../precios-y-licitaciones',
  },
  // {
  //   id: 4,
  //   title: 'GESTIÓN DE COMPROMISOS',
  //   img: 'gestion_compromisos',
  //   alt: 'Gestión de compromisos',
  //   descripcion: 'En esta sección, se detallan los compromisos del municipio relacionados con obras públicas, incluyendo proyectos en curso y futuros. Los ciudadanos pueden seguir el avance de las obras, conocer los plazos y presupuestos, y verificar el cumplimiento de los compromisos, promoviendo la transparencia y el control sobre el uso de los recursos públicos.',
  //   link: '../GestionComprom',
  // },
  {
    id: 5,
    title: 'PRESUPUESTO PÚBLICO',
    img: 'presupuesto_publico',
    alt: 'Presupuesto público',
    descripcion: 'Esta sección ofrece detalles sobre ingresos y gastos del municipio, incluyendo documentos, gráficos y reportes para asegurar transparencia y rendición de cuentas.',
    link: '../presupuesto-publico',
  },
  {
    id: 6,
    title: 'GUIA MUNICIPAL',
    img: 'presupuesto_publico',
    alt: 'Guia municipal',
    descripcion: 'guia municipal',
    link: '../guia-municipal',
  },
  {
    id: 7,
    title: 'GUIA DE TRAMITES',
    img: 'presupuesto_publico',
    alt: 'Guia de tramites',
    descripcion: 'guia de tramites',
    link: '../guia-de-tramites',
  },
  {
    id: 8,
    title: 'CONTACTOS',
    img: 'presupuesto_publico',
    alt: 'CONTACTOS',
    descripcion: 'Sección donde encontra todos los contactos pertinentes al Municipio de Baradero',
    link: '../contactos',
  }
]
